# Generated by Django 5.1.3 on 2024-12-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_we_offer_text', models.CharField(max_length=350)),
                ('about_us_content_1', models.CharField(max_length=350)),
                ('about_us_content_2', models.CharField(max_length=350)),
                ('about_us_content_3', models.CharField(max_length=350)),
                ('about_us_content_4', models.CharField(max_length=350)),
                ('about_image_1', models.FileField(upload_to='about_images/')),
                ('about_image_2', models.FileField(upload_to='about_images/')),
                ('about_image_3', models.FileField(upload_to='about_images/')),
                ('our_mission_heading', models.CharField(max_length=200)),
                ('our_mission_content', models.CharField(max_length=500)),
                ('core_value_heading_1', models.CharField(max_length=100)),
                ('core_value_content_1', models.CharField(max_length=300)),
                ('core_value_heading_2', models.CharField(max_length=100)),
                ('core_value_content_2', models.CharField(max_length=300)),
                ('core_value_heading_3', models.CharField(max_length=100)),
                ('core_value_content_3', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_content', models.CharField(max_length=500)),
                ('category_image', models.FileField(upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_image', models.FileField(upload_to='client_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_nummber', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.FileField(upload_to='feature_projects_images/')),
                ('feature_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=50)),
                ('founder_position', models.CharField(max_length=100)),
                ('founder_description', models.CharField(max_length=500)),
                ('founder_image', models.FileField(upload_to='founder_images/')),
                ('founder_linkedin', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JoinU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_nummber', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=50)),
                ('partner_image', models.FileField(upload_to='partner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.FileField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_content_1', models.CharField(max_length=250)),
                ('solution_content_2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=50)),
                ('testimonial_position', models.CharField(max_length=50)),
                ('testimonial_brand', models.CharField(max_length=50)),
                ('testimonial_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_image', models.FileField(upload_to='project_images/')),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ieplapp.projectcategorie')),
            ],
        ),
    ]
