# Generated by Django 5.1.3 on 2024-12-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieplapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.FileField(upload_to='index_slider_images/')),
            ],
        ),
    ]
