# Generated by Django 5.1.3 on 2024-12-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieplapp', '0002_indexsliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_content', models.CharField(max_length=500)),
                ('blog_image', models.FileField(unique='blog_post_images/', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_content_1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_content_2',
            field=models.CharField(max_length=500),
        ),
    ]
