# Generated by Django 5.1.3 on 2024-12-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieplapp', '0003_blog_alter_solution_solution_content_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_dateday',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_datemonth',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
