# Generated by Django 5.1.3 on 2025-01-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieplapp', '0004_blog_blog_dateday_blog_blog_datemonth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactu',
            old_name='phone_nummber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='joinu',
            old_name='phone_nummber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.FileField(upload_to='blog_post_images/'),
        ),
    ]
